#!/usr/bin/env bash
set -e

# Default settings
real_path="$(readlink -f "$0")"
export PRAX_ROOT="$(dirname "$(dirname "$real_path")")"
libexec_path="$PRAX_ROOT/libexec"
export PRAX_HOSTS="$HOME/.prax"
export PATH="${libexec_path}:$PATH"

# User settings
[ -f "$HOME/.praxconfig" ] && source "$HOME/.praxconfig"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec prax-help
  ;;
* )
  command_path="$(command -v "prax-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "prax: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
