#!/bin/sh
### BEGIN INIT INFO
# Provides:       prax
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Prax Rack server (iptables configuration).
### END INIT INFO
set +e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/prax/bin/prax
NAME=prax
DESC="Prax Rack server (iptables configuration)."

prax iptables $1
